spring:
  application:
    name: ap-backend-api

  r2dbc:
    url: r2dbc:mysql://localhost:3306/accounts_payable_db
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    initialization-mode: always

  datasource:
    url: jdbc:mysql://localhost:3306/accounts_payable_db?useSSL=false
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    schemas: accounts_payable_db

management:
  endpoints:
    web:
      exposure:
        include: "*"